### ISSUE TITLE
the destination asset don't appear the information?

### ISSUE THREAD

**Issue by newbie-coin** [yuichiroaoki/poly-flashloan-bot#34]
Thank you for your share! 

When I run the code, the output don't have the destination asset info as below photo. Do you have any idea about it? 
<img width="1194" alt="截屏2022-01-25 上午12 25 52" src="https://user-images.githubusercontent.com/71858904/150824195-2f584c1f-9e0f-4b49-87b4-544c1476304b.png">

**Comment by yuichiroaoki** [comment]
I just updated the code. Probably fixed that

**Comment by newbie-coin** [comment]
I use the new code, but so pity it still not work as below. The problem maybe what reason caused🧐🧐?

Thank you!

<img width="1194" alt="截屏2022-01-25 下午1 49 35" src="https://user-images.githubusercontent.com/71858904/150919330-653c39f6-ced0-468e-977e-37203207f0ab.png">

 
<img width="1195" alt="截屏2022-01-25 下午1 49 29" src="https://user-images.githubusercontent.com/71858904/150919321-8eb19dd9-673f-4ec9-8461-1cb96f9b7781.png">

**Comment by newbie-coin** [comment]
I have been solved the problem. 

Sorry, because in some country, have to set the special network, I ignored the problem. 

Thank you again for your share and reply!
